name: Tests

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run tests
        run: uv run --frozen pytest

  lint:
    runs-on: ubuntu-latest
    name: Formatting and linting

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Code style (ruff)
        run: uv run --frozen ruff format --diff

      - name: Semantic checks (ruff)
        run: uv run --frozen ruff check

  types:
    runs-on: ubuntu-latest
    name: Typechecking

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Type checks
        run: uv run --frozen basedpyright

  coverage:
    runs-on: ubuntu-latest
    name: Calculating coverage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run tests & generate coverage
        run: uv run --frozen coverage run -m pytest

      - name: Display coverage report
        run: uv run --frozen coverage report --omit="tests/*"
